[app]
# Address to listen.
address = "0.0.0.0:9000"

# No trailing slashes.
root_url = "http://localhost:9000"

name = "Niltalk chat"

max_rooms = 1000
max_peers_per_room = 25

# Peer handle format (%s for ID) for peers who don't pick handles.
peer_handle_format = "Peer:%s"

# Length of the randomly generated room ID.
room_id_length = 8

# The number of messages and events (join / leave) etc. that has to be cached
# in a room to send to peers when they first join.
max_cached_messages = 100

# Maximum message length in bytes.
max_message_length = 3000

# Permitted message rate (messages / interval) after which a peer is kicked.
rate_limit_messages = 25
rate_limit_interval = "3s"

# How long will the room id persist in the db before first use?
room_age = "24h"

# Timeout in seconds for which the server will wait when sending
# a message to a peer before closing the connection. Useful for
# kicking out peers with slow connections.
websocket_timeout = "3s"

# Session cookie name.
session_cookie = "niltoken"

# Storage kind, one of redis|memory|fs.
storage = "redis"

[tor]
enabled=true
ssl=true
# Path to the tor private key path, leave it empty to store your key within the store.
privatekey=""

[ssl]
address=":443" # the listen address of the ssl/tls listener
enabled=true
# kind of ssl certificate sources, one of files|letsencrypt|auto
kind="auto"
# path to the private key file of your certificate, only for kind=files
privatekey=""
# path to the certificate file, only for kind=files
certificate=""
# the list of domains to get certificate for, only for kind=letsencrypt
domains= [ "yourdomain.com", "www.yourdomain.com" ]

[rooms]
  [rooms.local]
  id="local"
  name="local"
  password=""
    [rooms.local.growl]
    message="{{.UserName}} is calling you. Open {{.URL}}"
    title="Niltalk notification"
    sound="beep.mp3"
    motd="Welcome message of the day, type /help to get commands help"
    [[rooms.local.users]]
    name="me1"
    password="azerty"
    growl=true
    [[rooms.local.users]]
    name="me2"
    password="azerty"

# Redis cache server.
# Rooms are cached until they expires. Messages are not cached.
[store]
address = "redis:6379" # Eg: 127.0.0.1:6379
password = ""
db = 0
active_conns = 100
idle_conns = 20
timeout = "3s"

prefix_room = "NIL:ROOM:%s"
prefix_session = "NIL:SESS:ROOM:%s"

# InMemory store config.
# [store]
# no options available.

# FileSystem store config.
# [store]
# path = "db.json"


# File upload configuration.
[upload]
max-memory="32MB"
max-upload-size="2MB"
max-age="1year"
rate-limit-count="10"
rate-limit-period="1minute"
rate-limit-burst="1"
